# CRP ID
dm_object_info_msgs/CrpId crp_id

# Beacon ID(list)
SignalId[] signal_id_list

# Intelligence generation moment
dm_object_info_msgs/TimestampIts time

# Signal status information
SignalState state

# Specific control operation flag
SpecificControlFlags specific_control_flags

EventCount event_count

# Countdown stop flag
CountDownStopFlag count_down_stop_flag

# List of light color output information
SignalLightInfo[] signal_light_info_list
