# 機器識別ID
DeviceId device_id
# 機器運用状態
DeviceStat device_stat

# 経度緯度高さ
dm_object_info_msgs/GeodeticSystem geodetic_system
dm_object_info_msgs/Latitude latitude
dm_object_info_msgs/Longitude longitude
dm_object_info_msgs/Altitude altitude

# 検知方位(最小) [deg * 80]
DirectionMin direction_min
# 検知方位(最大) [deg * 80]
DirectionMax direction_max
# 検知距離(最小) [m]
DistanceMin distance_min
# 検知距離(最大) [m]
DistanceMax distance_max
