# Free space ID
dm_object_info_msgs/ObjectId id

# Information acquisition time
dm_object_info_msgs/TimestampIts time

# Presence reliability
dm_object_info_msgs/ExistenceConfidence existency

# Detection failure target size
dm_object_info_msgs/ObjectDimensionValue minimal_detectable_size

# Start position
dm_object_info_msgs/Location position_begin

# End position
dm_object_info_msgs/Location position_end

# Length
dm_object_info_msgs/ObjectDimension length

# Starting target ID
dm_object_info_msgs/ObjectId id_begin

# End target ID
dm_object_info_msgs/ObjectId id_end

# Source information
dm_object_info_msgs/ObjectId[] information_source_list
