# It represents the display direction of the blue arrow lamp, and the bit of the target direction is turned ON.
# "bit7: left diagonally backward" "bit6: left" "bit5: left diagonally forward" "bit4: go straight" "bit3: right diagonally forward" "bit2: right" "bit1: right diagonally backward" "bit0: U-turn "
# Regardless of the shape of the intersection, the direction indicated by the blue arrow light fixture shall be taken.

uint8 value 0
